# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'WAKeyValuePersistenceStoreDemo' do
    
pod 'WAKeyValuePersistenceStore', :path => '../WAKeyValuePersistenceStore/'

end

target 'WAKeyValuePersistenceStoreDemoTests' do
    
pod 'WAKeyValuePersistenceStore', :path => '../WAKeyValuePersistenceStore/'

end